# Generated by Django 4.1.4 on 2023-05-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('material_code', models.IntegerField(primary_key=True, serialize=False)),
                ('material_type', models.CharField(choices=[('Material', 'Material'), ('Other', 'Other')], max_length=100)),
                ('item_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond')], max_length=100)),
                ('material_name', models.CharField(max_length=100)),
                ('purity_perc', models.IntegerField()),
                ('hsn_code', models.CharField(choices=[('7113', '7113'), ('7114', '7114'), ('7115', '7115')], max_length=100)),
                ('purchase_rate', models.IntegerField()),
                ('units', models.CharField(choices=[('GMS', 'GMS'), ('GMA', 'GMA')], max_length=100)),
                ('selling_price', models.IntegerField()),
                ('open_gtm_grs_wt', models.IntegerField()),
                ('current_gtm_grs_wt', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('wastage', models.CharField(max_length=100)),
            ],
        ),
    ]
