# Generated by Django 4.1.4 on 2023-05-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='party',
            fields=[
                ('party_code', models.IntegerField(primary_key=True, serialize=False)),
                ('party_type', models.CharField(max_length=100)),
                ('party_turnover', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=100)),
                ('sub_type', models.CharField(max_length=100)),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('door_no_street', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(max_length=6)),
                ('phone', models.IntegerField(max_length=100)),
                ('mobile', models.IntegerField(max_length=100)),
                ('tin_no', models.IntegerField()),
                ('email', models.IntegerField()),
                ('state_name', models.CharField(max_length=100)),
                ('hmc_no', models.CharField(max_length=100)),
                ('pan_no', models.CharField(max_length=100)),
                ('state_code', models.IntegerField()),
                ('gstin', models.IntegerField()),
                ('current_balance', models.IntegerField()),
                ('delivery_address', models.CharField(max_length=100)),
            ],
        ),
    ]
