# Generated by Django 4.1.4 on 2023-05-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_turnover',
            field=models.CharField(choices=[('10cr', '10cr'), ('20cr', '20cr'), ('30cr', '30cr'), ('40cr', '40cr')], max_length=100),
        ),
    ]
