# Generated by Django 4.1.4 on 2023-05-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_party_party_turnover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
