# Generated by Django 4.1.4 on 2023-05-30 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_party_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='hsn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgst_per', models.IntegerField()),
                ('cgst_per', models.IntegerField()),
                ('igst_per', models.IntegerField()),
                ('hsn_code1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material')),
            ],
        ),
    ]
