# Generated by Django 4.1.4 on 2023-05-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsn',
            name='hsn_code1',
            field=models.IntegerField(),
        ),
    ]
