# Generated by Django 4.1.4 on 2023-05-31 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_hsn_hsn_code1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsn',
            name='id',
        ),
        migrations.AlterField(
            model_name='hsn',
            name='hsn_code1',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('bill_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_no', models.IntegerField(unique=True)),
                ('bill_date', models.DateField()),
                ('order_date', models.DateField()),
                ('balance', models.IntegerField()),
                ('turn_over', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('pay_type', models.CharField(max_length=100)),
                ('gst_type', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('order_no1', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('pcs', models.IntegerField()),
                ('bill_wt', models.IntegerField()),
                ('purity', models.IntegerField()),
                ('rate_grm', models.IntegerField()),
                ('total_rate', models.IntegerField()),
                ('jewel_wt', models.IntegerField()),
                ('st_wt', models.IntegerField()),
                ('new_wt', models.IntegerField()),
                ('total_wt', models.IntegerField()),
                ('tds_applicable', models.CharField(max_length=100)),
                ('tcs', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
                ('delivery_add', models.CharField(max_length=100)),
                ('cgst1', models.IntegerField()),
                ('r_off', models.IntegerField()),
                ('printing_type', models.CharField(max_length=100)),
                ('duplicate', models.CharField(max_length=100)),
                ('empty', models.CharField(max_length=100)),
                ('sgst', models.IntegerField()),
                ('igst', models.IntegerField()),
                ('total', models.IntegerField()),
                ('tcs_applicable', models.CharField(max_length=100)),
                ('huid', models.CharField(max_length=100)),
                ('hsn_code2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hsn')),
            ],
        ),
    ]
