# Generated by Django 4.1.4 on 2023-05-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_hsn_id_alter_hsn_hsn_code1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='gst_type',
            field=models.CharField(choices=[('SGST', 'SGST'), ('SGSA', 'SGSA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='item_name',
            field=models.CharField(choices=[('NEW GOLD', 'NEW GOLD'), ('OLD GOLD', 'OLD GOLD')], max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pay_type',
            field=models.CharField(choices=[('RTGS', 'RTGS'), ('RTMA', 'RTMA')], max_length=100),
        ),
    ]
