# Generated by Django 4.1.4 on 2023-06-01 05:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_duplicate_invoice_duplicate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Duplicate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Triplicate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='delivery_add',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='huid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tcs_applicable',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tds_applicable',
        ),
        migrations.AlterField(
            model_name='material',
            name='material_code',
            field=models.IntegerField(default=app.models.from_1, primary_key=True, serialize=False),
        ),
    ]
